---
- hosts: golang

  environment:
      PATH: /home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin

  tasks:

    - name: apt-get update
      apt:
        update-cache: yes
      changed_when: 0
      become: yes

    - name: download glang package
      command: wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
      become: yes

    - name: extract golang package
      command: tar -C /usr/local -xzf go1.12.7.linux-amd64.tar.gz
      become: yes

    - name: Kill running processes
      ignore_errors: yes
      command: fuser -k 8080/tcp

    - name: start golang app
      shell: nohup go run example/outyet/main.go > /dev/null 2>&1 &

    - name: clone git repo
      git:
       repo: 'https://github.com/golang/example.git'
       dest: /home/ubuntu/example
